module: Configuration
author: IBM and the Kitura project authors
github_url: https://github.com/Kitura/Configuration/

theme: fullwidth
clean: true
exclude: [Packages]

readme: README.md

skip_undocumented: false
hide_documentation_coverage: false

xcodebuild_arguments: [-project, Configuration.xcodeproj, -target, Configuration, LIBRARY_SEARCH_PATHS=.build/debug]
