app:
  image: ibmcom/swift-ubuntu:3.1.1
  ports:
    - "8080:8080"
  volumes:
    - .:/Configuration
  command: bash -c "cd /Configuration && swift package --build-path .build-ubuntu clean && swift build --build-path .build-ubuntu && swift test"

